import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PageCache } from '../../src/main/resources/static/page-cache.js';
import { progressView } from '../../src/main/resources/static/page-progress.js';
const cache = new PageCache(3, 2000);
cache.set(1, {revision: 1});cache.set(2, {revision: 2});cache.set(3, {revision: 3});
cache.get(1);cache.set(4, {revision: 4});
assert.equal(cache.has(2), false);assert.equal(cache.has(1), true);assert.equal(cache.size, 3);
cache.set(4, {text: 'x'.repeat(3000)});assert.equal(cache.has(4), false);assert.ok(cache.bytes <= 2000);
cache.clear();assert.equal(cache.bytes, 0);assert.equal(cache.size, 0);
assert.equal(progressView({lifecycle:'RUNNING',percent:62},'READY').text,'处理中 · 62%');
assert.equal(progressView({lifecycle:'PARTIAL',percent:75},'READY').hidden,false);
assert.equal(progressView({lifecycle:'SUCCEEDED',percent:100},'READY').hidden,true);
assert.equal(progressView(null,'PENDING').percent,0);
assert.equal(progressView({lifecycle:'RUNNING',percent:999},'READY').percent,100);
const html=await readFile(new URL('../../src/main/resources/static/index.html',import.meta.url),'utf8');
assert.match(html,/id="page-save-status"[^>]*>[^<]*<\/span><span id="page-processing-progress"/);
const app=await readFile(new URL('../../src/main/resources/static/app.js',import.meta.url),'utf8');
const select=app.slice(app.indexOf('async function selectBook'),app.indexOf('function validateRange'));
assert.ok(select.indexOf('await goToPage') < select.indexOf('api.pages(id)'), 'current page before whole-book summaries');
const api=await readFile(new URL('../../src/main/resources/static/api.js',import.meta.url),'utf8');
assert.match(api,/await response\.json\(\)/,'response body remains under timeout');
console.log('PASS: LRU byte/page bounds, progress states/placement, current-page-first critical path, body timeout');

const { loadPreferences, getBookmarks } = await import('../../src/main/resources/static/store.js');
globalThis.localStorage = {getItem: () => 'null'};
assert.deepEqual(loadPreferences('b'), {});assert.deepEqual(getBookmarks('b'), []);
globalThis.localStorage = {getItem: () => '[1,2,-1,"3",null,1]'};
assert.deepEqual(loadPreferences('b'), {});assert.deepEqual(getBookmarks('b'), [1,2]);
console.log('PASS: malformed stored preferences/bookmarks cannot break book opening');
